### PR TITLE
Add homeassistant mqtt discovery

### PR DESCRIPTION
**Pull request by nhangeland**
Discovery automatically configures the controller as a HVAC fan only device in homeassistant.

Enable by uncommenting ```#define useHomeassistant``` in config.h

image

image

### CODE REVIEW

**Comment by KlausMu** [comment]
Thanks a lot for your PR!
I tried it, but for me the discovery is not really working in my HA installation. But I'm not very familiar with mqtt discovery. Maybe you can help me out.
I can see in MQTT Explorer that the discovery message was sent.
20231107_195018_543_MQTT_Explorer
In  HA I see that only one entity was created, not more.
20231107_195251_077_chrome
In the log there is nothing suspicious.
Do you have an idea?

**Comment by nhangeland** [comment]
You should get the controls if you click the entity. Or did you think its strange because its just an entity without any parent device?

**Comment by KlausMu** [comment]
Hm, yes, probably you are right. I expected a device. Or at least more than one entity (one for humidity, one for temp and so on). Seems I still have to learn something about HA ...
Ok, great. May I use your screenshots and add them to the wiki?

**Comment by nhangeland** [comment]
Of course you can use the screenshots. But wait with the merge, it seems like i'm having some problems with persistence. Discovery might need to run on a regular interval, I will look into it after work today. This is the first time i'm playing with discovery as well so still learning. I also didn't think about adding temp/humidity/altitude stats as additional entities, but it sounds like a good idea. I will play some more with it and let you know once it's ready.

**Comment by KlausMu** [comment]
Ok, thanks. Wiki is already finished: [06 Home Assistant](https://github.com/KlausMu/esp32-fan-controller/wiki/06-Home-Assistant)

**Comment by KlausMu** [comment]
@nhangeland Maybe you want to jump into this discussion https://github.com/KlausMu/esp32-fan-controller/issues/15

**Pull request merged**
